import { MenuVo } from "./common.interface";

export const TMP_NAVIGATION: MenuVo[] = [
  {
    name: "Underwriting",
    path: "uw",
    selected: false,
    children: [
      {
        name: "고객",
        path: "#",
        selected: false,
        children: [
          { name: "고객목록조회", path: "uw/uw1000" },
          { name: "통합고객관리", path: "uw/uw1010" },
          { name: "출자금관리", path: "uw/uw1020" },
          { name: "출자금목록조회", path: "uw/uw1021" },
          { name: "통합고객관리_선사", path: "uw/uw1011" },
        ],
      },
      {
        name: "영업관리",
        path: "#",
        children: [
          { name: "거래처목록조회", path: "uw/uw1100" },
          { name: "선사영업관리", path: "uw/uw1110" },
          { name: "영업활동이력관리", path: "uw/uw1121" },
          { name: "연락처관리", path: "uw/uw1130" },
        ],
      },
      {
        name: "상품관리",
        path: "#",
        children: [
          { name: "선박목록조회", path: "uw/uw2030" },
          { name: "선박관리", path: "uw/uw2040" },
          { name: "상품관리", path: "uw/uw2000" },
          { name: "상품담보관리", path: "uw/uw2001" },
          { name: "항해구역관리_Trading Area", path: "uw/uw2003" },
          { name: "출력문구관리", path: "uw/uw2002" },
          { name: "항구코드관리", path: "uw/uw2004" },
          { name: "Issuing State Code", path: "uw/uw2006" },
        ],
      },
      {
        name: "신계약",
        path: "#",
        children: [
          { name: "갱신가입설계", path: "uw/uw2150" },
          { name: "상품가입설계(SOL)", path: "uw/uw2120" },
          { name: "상품가입설계(CLI)", path: "uw/uw2130" },
        ],
      },
      {
        name: "계약변경",
        path: "#",
        children: [
          { name: "계약변경이력", path: "uw/uw2201" },
          { name: "계약변경신청", path: "uw/uw2200" },
          { name: "휴항환급변경", path: "uw/uw2202" },
          { name: "선급담보유예변경", path: "uw/uw2203" },
          { name: "보험료변경", path: "uw/uw2204" },
          { name: "담보정지", path: "uw/uw2205" },
          { name: "해제/해지", path: "uw/uw2206" },
          { name: "변경설계(SOL)", path: "uw/uw2220" },
          { name: "변경설계(CLI)", path: "uw/uw2230" },
        ],
      },
      {
        name: "계약관리",
        path: "#",
        children: [
          { name: "설계목록조회", path: "uw/uw2300" },
          { name: "계약목록조회", path: "uw/uw2301" },
          { name: "경과보험료", path: "uw/uw2302" },
          { name: "보험료관리", path: "uw/uw2304" },
          { name: "지급관리", path: "uw/uw2305" },
          { name: "납입스케줄관리", path: "uw/uw2306" },
          { name: "중개사목록조회", path: "uw/uw2305" },
          { name: "중개수수료관리", path: "uw/uw2307" },
          { name: "손해율조회", path: "uw/uw2310" },
          { name: "계약갱신관리", path: "uw/uw2311" },
          { name: "갱신결과조회", path: "uw/uw2312" },
        ],
      },
      {
        name: "통합출력물",
        path: "#",
        children: [
          { name: "통합발행관리", path: "uw/uw2410" },
          { name: "통합문서관리", path: "uw/uw2420" },
          { name: "요율안내서_통합", path: "uw/uw2430" },
          { name: "요율안내서_OpenCover", path: "uw/uw2431" },
          { name: "Certificate-가입증서", path: "uw/uw2434" },
          { name: "Invoice(Annual Premium) - 단선", path: "uw/uw2435" },
          {
            name: "Invoice(Annual Premium) - 2척 이상",
            path: "uw/uw2436",
          },
          {
            name: "Endorsement(배서)_계약조건 변경시 발행",
            path: "uw/uw2438",
          },
          {
            name: "Loss Ratio Record_선사별 이재율표",
            path: "uw/uw2450",
          },
          { name: "임금채권보장보험 가입증서", path: "uw/uw2451" },
          { name: "임금채권보장보험 Invoice", path: "uw/uw2452" },
        ],
      },
    ],
  },
  {
    name: "Reinsurance",
    path: "re",
    children: [
      {
        name: "재보험 현황",
        path: "#",
        children: [
          { name: "재보험 스케줄현황 관리", path: "re/re5000" },
          { name: "재보험료 현황", path: "re/re5010" },
          { name: "재보험금 현황", path: "re/re5020" },
          { name: "Bordereaux 관리", path: "re/re5200" },
        ],
      },
      {
        name: "재보험 문서",
        path: "#",
        children: [
          { name: "문서관리", path: "re/re5210" },
          { name: "최소보험료 관리", path: "re/re5110" },
          { name: "최소보험료초과분 관리", path: "re/re5120" },
          { name: "환급보험료 관리 ", path: "re/re5130" },
          { name: "복원보험료 관리", path: "re/re5140" },
          { name: "이익수수료 관리", path: "re/re5150" },
          { name: "재보험 문서료 정정", path: "re/re5160" },
          { name: "FAC재보험료 등록", path: "re/re5170" },
          { name: "FAC재보험금 등록", path: "re/re5180" },
        ],
      },
      { name: "재보험 상세", path: "#", children: [] },
      {
        name: "재보험 시뮬레이션",
        path: "#",
        children: [
          { name: "시뮬레이션정보 EPI 등록 ", path: "re/re5310" },
          { name: "시뮬레이션정보 Claim 등록", path: "re/re5320" },
          {
            name: "시뮬레이션정보 재보험구조 관리",
            path: "re/re5330",
          },
          {
            name: "시뮬레이션정보 재보험옵션 관리",
            path: "re/re5340",
          },
          { name: "재보험 시뮬레이션 실행", path: "re/re5300" },
          { name: "재보험 시뮬레이션 결과보고 ", path: "re/re5350" },
        ],
      },
      { name: "재보험 산출식관리", path: "re/rinscalc", children: [] },
    ],
  },
  {
    name: "Claim",
    path: "cl",
    children: [
      {
        name: "외부업체관리",
        path: "#",
        children: [
          { name: "Claim 목록 조회 (Claim List)", path: "cl/cl3004" },
          { name: "Claim", path: "cl/cl3006" },
          {
            name: "판례 및 선행처리 관리 (판례 및 선행처리 관리)",
            path: "cl/cl3000",
          },
          {
            name: "보상업무 업체 평가정보 목록 (업체평가 관리)",
            path: "cl/cl3002",
          },
          {
            name: "보증장 발행, 회수 관리 (보증장관리)",
            path: "cl/cl3900",
          },
          { name: "공문관리 화면 (공문관리)", path: "cl/cl3901" },
          {
            name: "보상 월마감 및 마감데이터 조회(월별 마감/결산)",
            path: "cl/cl3100",
          },
          { name: "보상 월마감 Overview", path: "cl/cl3101" },
          { name: "OS 대비 지급실적", path: "cl/cl3102" },
        ],
      },
      { name: "사고접수/진행", path: "#", children: [] },
      { name: "통계", path: "#", children: [] },
      { name: "기타", path: "#", children: [] },
    ],
  },
  {
    name: "LP",
    path: "lp",
    children: [
      {
        name: "선박위험관리",
        path: "#",
        children: [
          {
            name: "Condition Survey 대상 선박 관리(대상선별 - 갱신전)",
            path: "lp/lp4000",
          },
          {
            name: "Condition Survey 대상 선박 관리(대상확인 - 갱신 및 계약후)",
            path: "lp/lp4010",
          },
          {
            name: "우선관리대상선박(Targeted Ship) 관리",
            path: "lp/lp4020",
          },
          { name: "LP Notice 관리", path: "lp/lp4040" },
        ],
      },
      {
        name: "Survey",
        path: "#",
        children: [
          { name: "Survery 목록조회", path: "lp/lp4110" },
          { name: "Survery", path: "lp/lp4100" },
        ],
      },
      {
        name: "기타",
        path: "#",
        children: [{ name: "검정업체정보관리", path: "lp/lp4200" }],
      },
    ],
  },
  {
    name: "Account",
    path: "ms",
    children: [
      {
        name: "지급",
        path: "#",
        children: [
          { name: "지출결의 관리", path: "ms/ms6000" },
          { name: "카드매입내역 목록", path: "ms/ms6002" },
          { name: "카드매입내역관리", path: "ms/ms6003" },
          { name: "전자계산서지급처리 관리", path: "ms/ms6004" },
          { name: "소액현금관리", path: "ms/ms6005" },
        ],
      },
      {
        name: "결산관리",
        path: "#",
        children: [
          { name: "입/출금처리", path: "ms/ms6100" },
          { name: "상계처리", path: "ms/ms6101" },
          { name: "정산결과관리", path: "ms/ms6102" },
          { name: "보험미수금 충당금 설정", path: "ms/ms6007" },
        ],
      },
    ],
  },
  {
    name: "Common",
    path: "cm",
    children: [
      {
        name: "업무공통",
        path: "#",
        children: [
          { name: "팀/부서정보관리", path: "cm/cm7300" },
          { name: "리멤버동기화", path: "cm/cm7303" },
          { name: "직원정보관리", path: "cm/cm7310" },
          { name: "근태신청", path: "cm/cm7000" },
          { name: "근태현황조회 (관리자/사용자)", path: "cm/cm7010" },
          { name: "일일근무현황 (관리자)", path: "cm/cm7020" },
          { name: "메뉴관리", path: "cm/cm7800" },
          { name: "Club DashBoard", path: "cm/cm7000" },
        ],
      },
      {
        name: "시스템",
        path: "#",
        children: [
          { name: "코드관리", path: "cm/cm7700" },
          { name: "환율조회", path: "cm/cm7710" },
          { name: "출력물양식관리", path: "cm/cm7600" },
          { name: "사용자권한 관리", path: "cm/cm7500" },
          { name: "권한그룹 설정", path: "cm/cm7510" },
          { name: "메뉴권한관리", path: "cm/cm7520" },
          { name: "프로그램관리", path: "cm/cm7810" },
          { name: "IT Request 신청", path: "cm/cm7900" },
        ],
      },
      {
        name: "Developer Reference",
        path: "#",
        children: [
          { name: "Data Grid", path: "cm/cm7901" },
          { name: "List View Modify", path: "cm/cm7902" },
          { name: "Input Form", path: "cm/cm7903" },
          { name: "Etc Component", path: "cm/cm7904" },
          { name: "Icon", path: "cm/cm7905" },
        ],
      },
    ],
  },
  {
    name: "Design",
    path: "design",
    children: [
      {
        name: "home",
        path: "design/home",
        selected: false,
      },
      {
        name: "login",
        path: "design/login",
        selected: false,
      },
      {
        name: "Underwriting",
        path: "#",
        selected: false,
        children: [
          { name: "고객 - 고객목록조회", path: "design/uw/uw1000" },
          { name: "고객 - 통합고객관리", path: "design/uw/uw1010" },
          { name: "고객 - 출자금관리", path: "design/uw/uw1020" },
          { name: "고객 - 출자금목록조회", path: "design/uw/uw1021" },
          { name: "고객 - 통합고객관리_선사", path: "design/uw/uw1011" },
          { name: "영업관리 - 거래처목록조회", path: "design/uw/uw1100" },
          { name: "영업관리 - 선사영업관리", path: "design/uw/uw1110" },
          { name: "영업관리 - 영업활동이력관리", path: "design/uw/uw1121" },
          { name: "영업관리 - 연락처관리", path: "design/uw/uw1130" },
          { name: "상품관리 - 선박목록조회", path: "design/uw/uw2030" },
          { name: "상품관리 - 선박관리", path: "design/uw/uw2040" },
          { name: "상품관리 - 상품관리", path: "design/uw/uw2000" },
          { name: "상품관리 - 상품담보관리", path: "design/uw/uw2001" },
          {
            name: "상품관리 - 항해구역관리_Trading Area",
            path: "design/uw/uw2003",
          },
          { name: "상품관리 - 출력문구관리", path: "design/uw/uw2002" },
          { name: "상품관리 - 항구코드관리", path: "design/uw/uw2004" },
          { name: "상품관리 - Issuing State Code", path: "design/uw/uw2006" },
          { name: "신계약 - 갱신가입설계", path: "design/uw/uw2150" },
          { name: "신계약 - 상품가입설계(SOL)", path: "design/uw/uw2120" },
          { name: "신계약 - 상품가입설계(CLI)", path: "design/uw/uw2130" },
          { name: "계약변경 - 계약변경이력", path: "design/uw/uw2201" },
          { name: "계약변경 - 계약변경신청", path: "design/uw/uw2200" },
          { name: "계약변경 - 휴항환급변경", path: "design/uw/uw2202" },
          { name: "계약변경 - 선급담보유예변경", path: "design/uw/uw2203" },
          { name: "계약변경 - 보험료변경", path: "design/uw/uw2204" },
          { name: "계약변경 - 담보정지", path: "design/uw/uw2205" },
          { name: "계약변경 - 해제/해지", path: "design/uw/uw2206" },
          { name: "계약변경 - 변경설계(SOL)", path: "design/uw/uw2220" },
          { name: "계약변경 - 변경설계(CLI)", path: "design/uw/uw2230" },
          { name: "계약관리 - 설계목록조회", path: "design/uw/uw2300" },
          { name: "계약관리 - 계약목록조회", path: "design/uw/uw2301" },
          { name: "계약관리 - 경과보험료", path: "design/uw/uw2302" },
          { name: "계약관리 - 보험료관리", path: "design/uw/uw2304" },
          { name: "계약관리 - 지급관리", path: "design/uw/uw2305" },
          { name: "계약관리 - 납입스케줄관리", path: "design/uw/uw2306" },
          { name: "계약관리 - 중개사목록조회", path: "design/uw/uw2305" },
          { name: "계약관리 - 중개수수료관리", path: "design/uw/uw2307" },
          { name: "계약관리 - 손해율조회", path: "design/uw/uw2310" },
          { name: "계약관리 - 계약갱신관리", path: "design/uw/uw2311" },
          { name: "계약관리 - 갱신결과조회", path: "design/uw/uw2312" },
          { name: "통합출력물 - 통합발행관리", path: "design/uw/uw2410" },
          { name: "통합출력물 - 통합문서관리", path: "design/uw/uw2420" },
          { name: "통합출력물 - 요율안내서_통합", path: "design/uw/uw2430" },
          {
            name: "통합출력물 - 요율안내서_OpenCover",
            path: "design/uw/uw2431",
          },
          {
            name: "통합출력물 - Certificate-가입증서",
            path: "design/uw/uw2434",
          },
          {
            name: "통합출력물 - Invoice(Annual Premium) - 단선",
            path: "design/uw/uw2435",
          },
          {
            name: "통합출력물 - Invoice(Annual Premium) - 2척 이상",
            path: "design/uw/uw2436",
          },
          {
            name: "통합출력물 - Endorsement(배서)_계약조건 변경시 발행",
            path: "design/uw/uw2438",
          },
          {
            name: "통합출력물 - Loss Ratio Record_선사별 이재율표",
            path: "design/uw/uw2450",
          },
          {
            name: "통합출력물 - 임금채권보장보험 가입증서",
            path: "design/uw/uw2451",
          },
          {
            name: "통합출력물 - 임금채권보장보험 Invoice",
            path: "design/uw/uw2452",
          },
        ],
      },
      {
        name: "Reinsurance",
        path: "#",
        children: [
          {
            name: "재보험 현황 - 재보험 스케줄현황 관리",
            path: "design/re/re5000",
          },
          { name: "재보험 현황 - 재보험료 현황", path: "design/re/re5010" },
          { name: "재보험 현황 - 재보험금 현황", path: "design/re/re5020" },
          { name: "재보험 현황 - Bordereaux 관리", path: "design/re/re5200" },
          { name: "재보험 문서 - 문서관리", path: "design/re/re5210" },
          { name: "재보험 문서 - 최소보험료 관리", path: "design/re/re5110" },
          {
            name: "재보험 문서 - 최소보험료초과분 관리",
            path: "design/re/re5120",
          },
          { name: "재보험 문서 - 환급보험료 관리 ", path: "design/re/re5130" },
          { name: "재보험 문서 - 복원보험료 관리", path: "design/re/re5140" },
          { name: "재보험 문서 - 이익수수료 관리", path: "design/re/re5150" },
          {
            name: "재보험 문서 - 재보험 문서료 정정",
            path: "design/re/re5160",
          },
          { name: "재보험 문서 - FAC재보험료 등록", path: "design/re/re5170" },
          { name: "재보험 문서 - FAC재보험금 등록", path: "design/re/re5180" },
          { name: "시뮬레이션정보 EPI 등록 ", path: "design/re/re5310" },
          { name: "시뮬레이션정보 Claim 등록", path: "design/re/re5320" },
          {
            name: "시뮬레이션정보 재보험구조 관리",
            path: "design/re/re5330",
          },
          {
            name: "시뮬레이션정보 재보험옵션 관리",
            path: "design/re/re5340",
          },
          { name: "재보험 시뮬레이션 실행", path: "design/re/re5300" },
          { name: "재보험 시뮬레이션 결과보고 ", path: "design/re/re5350" },
        ],
      },
      {
        name: "Claim",
        path: "#",
        children: [
          {
            name: "외부업체관리 - Claim 목록 조회 (Claim List)",
            path: "design/cl/cl3004",
          },
          { name: "외부업체관리 - Claim", path: "design/cl/cl3006" },
          {
            name: "외부업체관리 - 판례 및 선행처리 관리 (판례 및 선행처리 관리)",
            path: "design/cl/cl3000",
          },
          {
            name: "외부업체관리 -  보상업무 업체 평가정보 목록 (업체평가 관리)",
            path: "design/cl/cl3002",
          },
          {
            name: "외부업체관리 -  보증장 발행, 회수 관리 (보증장관리)",
            path: "design/cl/cl3900",
          },
          {
            name: "외부업체관리 -  공문관리 화면 (공문관리)",
            path: "design/cl/cl3901",
          },
          {
            name: "외부업체관리 - 보상 월마감 및 마감데이터 조회(월별 마감/결산)",
            path: "design/cl/cl3100",
          },
          {
            name: "외부업체관리 - 보상 월마감 Overview",
            path: "design/cl/cl3101",
          },
          { name: "OS 대비 지급실적", path: "design/cl/cl3102" },
        ],
      },
      {
        name: "LP",
        path: "#",
        children: [
          {
            name: "선박위험관리 - Condition Survey 대상 선박 관리(대상선별 - 갱신전)",
            path: "design/lp/lp4000",
          },
          {
            name: "선박위험관리 - Condition Survey 대상 선박 관리(대상확인 - 갱신 및 계약후)",
            path: "design/lp/lp4010",
          },
          {
            name: "선박위험관리 - 우선관리대상선박(Targeted Ship) 관리",
            path: "design/lp/lp4020",
          },
          {
            name: "선박위험관리 - LP Notice 관리",
            path: "design/lp/lp4040",
          },
          { name: "Survery 목록조회", path: "design/lp/lp4110" },
          { name: "Survery", path: "design/lp/lp4100" },
          { name: "검정업체정보관리", path: "design/lp/lp4200" },
        ],
      },
      {
        name: "Account",
        path: "#",
        children: [
          { name: "지급 - 지출결의 관리", path: "design/ms/ms6000" },
          { name: "지급 -  카드매입내역 목록", path: "design/ms/ms6002" },
          { name: "지급 -  카드매입내역관리", path: "design/ms/ms6003" },
          {
            name: "지급 - 전자계산서지급처리 관리",
            path: "design/ms/ms6004",
          },
          { name: "지급 - 소액현금관리", path: "design/ms/ms6005" },
          { name: "결산관리 - 입/출금처리", path: "design/ms/ms6100" },
          { name: "결산관리 - 상계처리", path: "design/ms/ms6101" },
          { name: "결산관리 - 정산결과관리", path: "design/ms/ms6102" },
          {
            name: "결산관리 - 보험미수금 충당금 설정",
            path: "design/ms/ms6007",
          },
        ],
      },
      {
        name: "Common",
        path: "#",
        children: [
          { name: "업무공통 - 팀/부서정보관리", path: "design/cm/cm7300" },
          { name: "업무공통 - 리멤버동기화", path: "design/cm/cm7303" },
          { name: "업무공통 - 직원정보관리", path: "design/cm/cm7310" },
          { name: "업무공통 - 근태신청", path: "design/cm/cm7000" },
          {
            name: "업무공통 - 근태현황조회 (관리자/사용자)",
            path: "design/cm/cm7010",
          },
          {
            name: "업무공통 - 일일근무현황 (관리자)",
            path: "design/cm/cm7020",
          },
          { name: "업무공통 - 메뉴관리", path: "design/cm/cm7800" },
          { name: "업무공통 - Club DashBoard", path: "design/cm/cm7000" },
          { name: "시스템 - 코드관리", path: "design/cm/cm7700" },
          { name: "시스템 - 환율조회", path: "design/cm/cm7710" },
          { name: "시스템 - 출력물양식관리", path: "design/cm/cm7600" },
          { name: "시스템 - 사용자권한 관리", path: "design/cm/cm7500" },
          { name: "시스템 - 권한그룹 설정", path: "design/cm/cm7510" },
          { name: "시스템 - 메뉴권한관리", path: "design/cm/cm7520" },
          { name: "시스템 - 프로그램관리", path: "design/cm/cm7810" },
          { name: "시스템 - IT Request 신청", path: "design/cm/cm7900" },
        ],
      },
    ],
  },
];
